compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
